version: '3'

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1496

services:
  traefik:
    image: traefik:v2.1
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - ./config/acme.json:/acme.json
    labels:
      # middleware redirect  
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https" 
      # middleware hsts 
      # - "traefik.http.middlewares.hsts.headers.framedeny=true"
      # - "traefik.http.middlewares.hsts.headers.sslredirect=true"
      - "traefik.http.middlewares.security_header.headers.stsPreload=true"
      - "traefik.http.middlewares.security_header.headers.stsSeconds=15552000"
      # global redirect to https  
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"  
      - "traefik.http.routers.redirs.entrypoints=web"  
      - "traefik.http.routers.redirs.middlewares=redirect-to-https" 
      
