providers:
  # Autodetect docker containers
  docker: {}

entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      email: archimist.linux@gmail.com
      storage: /acme.json
      httpChallenge:
        # Use HTTP for challenge
        # TODO: TLS-ALPN-01 is recommanded
        # See https://docs.traefik.io/https/acme/
        entryPoint: web
