version: '3'

services:

  #############################################################################
  # Database
  erdnaxe_mysql:
    image: mariadb:10.4
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${ERDNAXE_ROOT_MYSQL_PASSWD}"
      - MYSQL_USER=ctfd
      - "MYSQL_PASSWORD=${ERDNAXE_CTFD_MYSQL_PASSWD}"
      - MYSQL_DATABASE=ctfd
    volumes:
      - "${DATA_ROOT}/erdnaxe/mysql:/var/lib/mysql"
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  erdnaxe_redis:
    image: redis:4
    restart: always
    volumes:
      - "${DATA_ROOT}/erdnaxe/redis:/data"

  #############################################################################
  # Monitoring
  erdnaxe_prometheus:
    image: prom/prometheus:v2.16.0
    volumes:
      - ./erdnaxe/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./erdnaxe/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - "${DATA_ROOT}/erdnaxe/prometheus:/prometheus"
    restart: always

  erdnaxe_alertmanager:
    image: prom/alertmanager:v0.20.0
    volumes:
      - ./erdnaxe/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    restart: always

  erdnaxe_cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

  erdnaxe_grafana:
    image: grafana/grafana
    volumes:
      - "${DATA_ROOT}/erdnaxe/grafana:/var/lib/grafana:rw"
    restart: always
    user: "104"
    environment:
      - GF_SESSION_COOKIE_SECURE=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_SNAPSHOTS_EXTERNAL_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.fr.to`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=le"

  #############################################################################
  # CTFd services
  erdnaxe_ctfd:
    image: ctfd/ctfd:latest
    user: root
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - "DATABASE_URL=mysql+pymysql://ctfd:${ERDNAXE_CTFD_MYSQL_PASSWD}@erdnaxe_mysql/ctfd"
      - REDIS_URL=redis://erdnaxe_redis:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - "REVERSE_PROXY=1,1,1,0,0"
      - MAILFROM_ADDR=ctf@crans.org
      - MAIL_SERVER=smtp.crans.org
      - MAIL_PORT=25
    volumes:
      - "${DATA_ROOT}/erdnaxe/CTFd/logs:/var/log/CTFd"
      - "${DATA_ROOT}/erdnaxe/CTFd/uploads:/var/uploads"
    depends_on:
      - erdnaxe_mysql
    labels:
      - "traefik.http.routers.ctfd.rule=Host(`ctf.adh.crans.org`)"
      - "traefik.http.services.ctfd.loadbalancer.server.port=8000"
      - "traefik.http.routers.ctfd.tls=true"
      - "traefik.http.routers.ctfd.tls.certresolver=le"

  #############################################################################
  # Sync services
  erdnaxe_syncserver:
    image: mozilla/syncserver:latest
    restart: always
    volumes:
      # owned by 1001:1001
      - "${DATA_ROOT}/erdnaxe/syncserver:/data:rw"
      # generate using `head -c 20 /dev/urandom | sha1sum`
      - "./erdnaxe/syncserver/secretfile:/secretfile:ro"
    environment:
      - TZ=Europe/Paris
      - SYNCSERVER_PUBLIC_URL=https://templier.adh.crans.org:5000
      - SYNCSERVER_SECRET_FILE=/secretfile
      - SYNCSERVER_SQLURI=sqlite:////tmp/syncserver.db
      - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
      - SYNCSERVER_FORCE_WSGI_ENVIRON=false
      - PORT=5000
