version: '3'

services:

  #############################################################################
  # Monitoring
  erdnaxe_prometheus:
    image: prom/prometheus:v2.16.0
    volumes:
      - ./erdnaxe/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./erdnaxe/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - "${DATA_ROOT}/erdnaxe/prometheus:/prometheus"
    restart: always

  erdnaxe_alertmanager:
    image: prom/alertmanager:v0.20.0
    volumes:
      - ./erdnaxe/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    restart: always

  erdnaxe_cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

  erdnaxe_grafana:
    image: grafana/grafana
    volumes:
      - "${DATA_ROOT}/erdnaxe/grafana:/var/lib/grafana:rw"
    restart: always
    user: "104"
    environment:
      - GF_SESSION_COOKIE_SECURE=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_SNAPSHOTS_EXTERNAL_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.fr.to`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=le"

  #############################################################################
  # Sync services
  erdnaxe_syncserver:
    image: mozilla/syncserver:latest
    restart: always
    volumes:
      # owned by 1001:1001
      - "${DATA_ROOT}/erdnaxe/syncserver:/data:rw"
      # generate using `head -c 20 /dev/urandom | sha1sum`
      - "./erdnaxe/syncserver/secretfile:/secretfile:ro"
    environment:
      - TZ=Europe/Paris
      - SYNCSERVER_PUBLIC_URL=https://templier.adh.crans.org:5000
      - SYNCSERVER_SECRET_FILE=/secretfile
      - SYNCSERVER_SQLURI=sqlite:////tmp/syncserver.db
      - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
      - SYNCSERVER_FORCE_WSGI_ENVIRON=false
      - PORT=5000
