global:
#  scrape_interval:     60s
#  evaluation_interval: 60s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets:
         - erdnaxe_alertmanager:9093

# Load rules once
# and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert.rules.yml"  # Monitoring alerts, this is the file you may be searching!

# Scrape configuration containing endpoints to scrape
scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: cadvisor
    static_configs:
      - targets: ['erdnaxe_cadvisor:8080']

  - job_name: servers
    static_configs:
      - targets:
        - 'templier.adh.crans.org'
    relabel_configs:
      # Do not put :9100 in instance name, rather here
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        target_label: __address__
        replacement: '$1:9100'
